// json-pointer-loc compiled to WebAssembly and encoded as a data URI
const wasmUri = `
    data:application/wasm;base64,AGFzbQEAAAABIQVgAABgA39/fwF/YAV/f39/fwF/YAF/AX9gBH9/f38BfwIPAQNlbnYGbWVtb3J5AgACAwcGAAECAwEEBj8KfwF
    BkK0EC38AQYAIC38AQZAtC38AQZAtC38AQZCtBAt/AEGACAt/AEGQrQQLfwBBgIAIC38AQQALfwBBAQsH0AENEV9fd2FzbV9jYWxsX2N0b3JzAAAOY29tcHV0ZV9jb2x
    1bW4AARFqc29uX3BvaW50ZXJuX2xvYwACEGpzb25fcG9pbnRlcl9sb2MABQxfX2Rzb19oYW5kbGUDAQpfX2RhdGFfZW5kAwILX19zdGFja19sb3cDAwxfX3N0YWNrX2h
    pZ2gDBA1fX2dsb2JhbF9iYXNlAwULX19oZWFwX2Jhc2UDBgpfX2hlYXBfZW5kAwcNX19tZW1vcnlfYmFzZQMIDF9fdGFibGVfYmFzZQMJCoAdBgIAC5YDAQZ/QQEhAwJ
    AIAEgAEYNACABIQQCQANAIAQtAABBCkYNASAEQX9qIgQgAEcNAAsgACEECyAEIAFPDQAgASAEayEFQQAhAEEBIQMDQCAELQAAIgZBgIiAgABqLQAAIQcCQAJAIABFDQA
    gBkE/cSABQQZ0ciEBDAELQf8BIAd2IAZxIQELAkAgByAAakGAioCAAGotAAAiAA0AAkACQAJAIAFB/gFLDQBBASEHIAFBAWpB/wBxQSBLDQEMAwsCQCABQf7/e3FB/f8
    DSw0AQQEgAUEHcXQiByABQQh2IgZB8IqAgABqLAAAQQV0IAFBA3ZBH3EiCHJB8IqAgABqLQAAcQ0DQQJBASAHIAZB0KCAgABqLAAAQQV0IAhyQdCggIAAai0AAHEbIQc
    MAQsgAUH+/wNxQf7/A0YNAkECIQcgAUGAgHhxQYCACEcNAQsgByADaiEDDAELIAMgAUHg/0dqQd8ASSABQYD+R2pB7wFJciABQYGAOEZyQX9zQQFxaiEDCyAEQQFqIQQ
    gBUF/aiIFDQALCyADC5cUAQ5/I4CAgIAAQRBrIgUkgICAgAACQAJAIAANAEEBIQYMAQsCQCACDQBBAiEGDAELAkAgA0UNAEEDIQYgAi0AAEEvRw0BQQAhByADIQhBASE
    JIAIhCkEAIQsDQCAJQQFxIQwgCi0AACINQYCIgIAAai0AACALakGAioCAAGotAAAhC0EAIQkCQCAMRQ0AAkAgBw0AQQEhCQwBCyANQf4BcUEwRiEJCyAKQQFqIQogDUH
    +AEYhByAIQX9qIggNAAsgC0EARyAJQQFzcg0BCyAAIAFqIQlBACELIAVBADYCDCAAIQoCQCABRQ0AIAAhCgJAA0ACQAJAAkAgCi0AACINQXdqDgUCAQQEAgALIA1BIEY
    NAQwDCyALQQFqIQsLIApBAWohCiABQX9qIgENAAsgCSEKCyAFIAs2AgwLIAIgA2ohDgJAAkAgA0UNACAKIAlGDQBBBSEGA0AgAkEBaiEPAkACQCAKLQAAIg1B2wBGDQA
    gDUH7AEcNBSAKQQFqIgogCUYNBSAFKAIMIQsCQANAAkACQAJAIAotAAAiDUF3ag4FAgAEBAIBCyAFIAtBAWoiCzYCDAwBCyANQSBHDQILIApBAWoiCiAJRw0ACyAJIQo
    LIAogCUYNBQNAIAotAABB/QBGDQYgCkEBaiIQIQwCQAJAIA8gDkYNACAPIQggECENAkACQANAIAgtAAAiDEUNAiAMQS9GDQIgDMAhCwJAIA0gCUcNACAJIQwMAgsCQCA
    NLQAAIhFFDQAgEUEiRg0AIBHAIQMCQAJAAkACQCALQQBIDQAgC0H+AEYNACADQQBIDQEgA0HcAEYNASALIANHDQkgDUEBaiEMIAhBAWohCAwDCyALQX9KDQBBACELAkA
    DQCAILQAAIgdBgIiAgABqLQAAIQwCQAJAIAtFDQAgB0E/cSACQQZ0ciECDAELQf8BIAx2IAdxIQILIAwgC2pBgIqAgABqLQAAIgtFDQEgCEEBaiIIIA5HDQALIA4hCAw
    CCyAIQQFqIQgMAQsCQCALQf4ARw0AIAhBAmohCEEvIQIMAQsgCEEBaiEIIAwhAgsCQAJAAkAgA0F/Sg0AQQAhCwNAIA0tAAAiB0GAiICAAGotAAAhDAJAAkAgC0UNACA
    HQT9xIAFBBnRyIQEMAQtB/wEgDHYgB3EhAQsCQCAMIAtqQYCKgIAAai0AACILRQ0AIA1BAWoiDSAJRw0BDAMLCyANQQFqIQwMAgsCQAJAAkACQCADQdwARw0AQf3/AyE
    BIA1BAWoiCyAJRg0EAkACQAJAAkACQAJAAkACQAJAIAstAAAiC0HhAEoNACALQSJGDQEgC0EvRg0CIAtB3ABHDQggDUECaiEMQdwAIQEMDgsCQCALQZ5/ag4FAwgICAQ
    ACyALQY5/ag4EBAcHBQYLIA1BAmohDEEiIQEMDAsgDUECaiEMQS8hAQwLCyANQQJqIQxBCCEBDAoLIA1BAmohDEEMIQEMCQsgDUECaiEMQQ0hAQwICyANQQZqIgsgCU8
    NBgJAIA0sAAIiB0FQaiIMQf8BcUEJTQ0AAkAgB0G/f2pB/wFxQQVLDQAgB0FJaiEMDAELIAdBqX9qQQAgB0Gff2pB/wFxQQZJGyEMCwJAIA0sAAMiA0FQaiIHQf8BcUE
    JTQ0AAkAgA0G/f2pB/wFxQQVLDQAgA0FJaiEHDAELIANBqX9qQQAgA0Gff2pB/wFxQQZJGyEHCwJAIA0sAAQiEUFQaiIDQf8BcUEJTQ0AAkAgEUG/f2pB/wFxQQVLDQA
    gEUFJaiEDDAELIBFBqX9qQQAgEUGff2pB/wFxQQZJGyEDCwJAIA0sAAUiEkFQaiIRQf8BcUEJTQ0AAkAgEkG/f2pB/wFxQQVLDQAgEkFJaiERDAELIBJBqX9qQQAgEkG
    ff2pB/wFxQQZJGyERCyAHQQh0IAxBDHRqIANBBHRqIBFqIgdBgPgDcUGAsANHDQMgCy0AAEHcAEcNBCANLQAHQfUARw0EIAkhDCANQQtqIAlPDQcgDUEIahCDgICAACI
    BQYD4A3FBgLgDRw0DIA1BDGohDCAHQQp0IAFqQYDIgGVqIQEMBwsgC0HuAEYNBAsgDUECaiEMDAULIA1BAWohDCARIQEMBAsgByEBCyALIQwMAgsgDUECaiEMQQohAQw
    BCyAJIQwLIAIgAUchDSACIQEgDQ0GCyAMIQ0gCCAORw0BDAQLCyANIQwLIAtFDQEMAgsgDSEMCwJAIAwgCUYNACAMLQAAIg1BIkYNACANDQELQQAhCwJAAkAgECAJRg0
    AAkADQAJAAkAgCi0AASINQdwARg0AIA1BIkYNAyAQIQoMAQsgCkECaiEKCyAKQQFqIhAgCUcNAAwCCwsgECAJRg0AIAUoAgwhDQNAAkACQCAQLQAAIgpBCkYNACAKQTp
    HDQFBASELDAQLIAUgDUEBaiINNgIMCyAQQQFqIhAgCUcNAAsLIAkhEAsCQCAQIAtqIgogCUYNACAFKAIMIQsDQAJAAkACQCAKLQAAIg1Bd2oOBQIACAgCAQsgBSALQQF
    qIgs2AgwMAQsgDUEgRw0GCyAKQQFqIgogCUcNAAsLIAkhCiAJDQMMBwsgCiAJIAVBDGoQhICAgAAiCiAJRg0GAkAgCi0AAEEsRw0AIApBAWoiCiAJRg0HIAUoAgwhCwJ
    AA0ACQAJAAkAgCi0AACINQXdqDgUCAQQEAgALIA1BIEYNAQwDCyALQQFqIQsLIApBAWoiCiAJRw0ACyAJIQoLIAUgCzYCDAsgCiAJRw0ADAYLC0EAIQgCQCAPIA5GDQA
    gDyENAkADQCANLQAAIgxBUGpB/wFxIgtBCUsNASAIQQpsIAtqIQggDUEBaiINIA5HDQAMAgsLIAxB/wFxQS9HDQULIApBAWoiCiAJRg0EIAUoAgwhCwJAA0ACQAJAAkA
    gCi0AACINQXdqDgUCAAQEAgELIAUgC0EBaiILNgIMDAELIA1BIEcNAgsgCkEBaiIKIAlHDQALIAkhCgsgCiAJRg0EQQAhDAJAA0AgCi0AAEHdAEYiDQ0BIAwgCE8NASA
    KIAkgBUEMahCEgICAACIKIAlGDQYCQCAKLQAAQSxHDQAgCkEBaiIKIAlGDQcgBSgCDCELAkADQAJAAkACQCAKLQAAIg1Bd2oOBQIBBAQCAAsgDUEgRg0BDAMLIAtBAWo
    hCwsgCkEBaiIKIAlHDQALIAkhCgsgBSALNgIMCyAMQQFqIQwgCiAJRw0ADAYLCyAMIAhHDQQgDQ0ECyAPIA5GDQICQANAIA8gDy0AAEH+AEZqIgItAABBL0YNASACQQF
    qIg8gDkcNAAwECwsgAiAORg0BIAogCUcNAAsLQQEhBiACIA5HDQELIAQgBSgCDEEBajYCBCAAIAogChCBgICAACEJIAQgCiAAazYCACAEIAk2AghBACEGCyAFQRBqJIC
    AgIAAIAYLxAIBBH8CQCAALAAAIgFBUGoiAkH/AXFBCU0NAAJAIAFBv39qQf8BcUEFSw0AIAFBSWohAgwBCyABQal/akEAIAFBn39qQf8BcUEGSRshAgsCQCAALAABIgN
    BUGoiAUH/AXFBCU0NAAJAIANBv39qQf8BcUEFSw0AIANBSWohAQwBCyADQal/akEAIANBn39qQf8BcUEGSRshAQsCQCAALAACIgRBUGoiA0H/AXFBCU0NAAJAIARBv39
    qQf8BcUEFSw0AIARBSWohAwwBCyAEQal/akEAIARBn39qQf8BcUEGSRshAwsCQCAALAADIgRBUGoiAEH/AXFBCU0NAAJAIARBv39qQf8BcUEFSw0AIARBSWohAAwBCyA
    EQal/akEAIARBn39qQf8BcUEGSRshAAsgACADQQR0IAFBCHQgAkEMdGpqagu1AgEEfwJAIAAgAUYNAEEAIQNBACEEAkADQAJAAkACQAJAAkACQAJAAkACQCAALQAAIgV
    B2gBKDQAgBUEKRg0GIAVBIkYNASAFQSxHDQcgBCADcg0HDAsLAkAgBUGlf2oOAwQHBQALIAVBhX9qDgMBBgIGCyAAQQFqIgUgAUYNCANAAkACQCAALQABIgZB3ABGDQA
    gBSEFIAZBIkcNASAAQQJqIQAMCQsgAEECaiEFCyAFIQAgBUEBaiIFIAFHDQAMCQsLIABBAWohACAEQQFqIQQMBQsgBCADckUNByAAQQFqIQAgBEF/aiEEDAQLIABBAWo
    hACADQQFqIQMMAwsgAEEBaiEAIANBf2ohAwwCCyACIAIoAgBBAWo2AgALIABBAWohAAsgACABRw0ACwsgASEACyAAC00BAn8CQCACDQBBAg8LQQAhBAJAA0ACQCACIAR
    qLQAADQAgBCEFDAILQYAIIQUgBEEBaiIEQYAIRw0ACwsgACABIAIgBSADEIKAgIAACwuYJQEAQYAIC5AlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQE
    BAQEBAQEBAQEBAQEBCQkJCQkJCQkJCQkJCQkJCQcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHCAgCAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIKAwM
    DAwMDAwMDAwMDBAMDCwYGBgUICAgICAgICAgICAAMGCQ8YFQMDAwwSAwMDAwMDAwMDAwMDAwADAwMDAwADAAMDAwYDAwMDAwYDBgMDAwMDAwMDAwYDAwMDAwYDAwMDAw
    MDBgMDAwMDAwMDAwkDCQMDAwkDAwMDAwkDCQMDAwkDAwMDAwMDAwMDAAAAAAQEBASExQVFhcYGRobHB0eHyAQIRAQECIjJCUmJygQECkQEBAQEBAQEBAQECorEBAsEBA
    QEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBA
    QEBAQEBAQEBAQEBAQEBAQEBAQLRAuLzAxEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEDIQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBA
    QEBAQEBAQEDMQEDQ1EDY3OBAQEBAQEDkQEDoQOzw9Pj9AQUJDREVGEEdISRAQEBAQEBAQEBAQEBAQEBAQEBAQEEoQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBA
    QEBAQEBAQEBAQEBAQEBAQEBAQEBAQEEtMEBAQTRAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBA
    QEBAQEBAQEBBOEBAQEBAQEBAQEBAQEBAQEBAQEBBPUBAQEBAQEBBREBAQEBBSU1QQEBAQEFVWEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAA/////////////////////////////////////////////////////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4AwA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/v////+/tgAAAAAAAAA/AP8XAAAAAAD4//8AAAEAAAAAAAAAAAAAAMC/nz0AAACAAgAAAP///wcAAAAAAAAAAAA
    AwP8BAAAAAAAA+A8gAADA++8+AAAAAAAOAAAAAAAAAAAAAAAAAAD4//////8HAAAAAAAAFP4h/gAMAAAAAgAAAAAAABAeIAAADAAAQAYAAAAAAAAQhjkCAAAAIwAGAAA
    AAAAAEL4hAAAMAAD8AgAAAAAAAJAeIEAADAAAAAQAAAAAAAAAASAAAAAAAAARAAAAAAAAwME9YAAMAAAAAgAAAAAAAJBAMAAADAAAAAMAAAAAAAAYHiAAAAwAAAAAAAA
    AAAAAAAAEXAAAAAAAAAAAAAAA8geAfwAAAAAAAAAAAAAAAPIfAD8AAAAAAAAAAAADAACgAgAAAAAAAP5/3+D//v///x9AAAAAAAAAAAAAAAAA4P1mAAAAwwEAHgBkIAA
    gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//////////////////////////8AAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAABwAAAAMAAAADAAAAAA
    AAACwP0D+DyAAAAAAAHgAAAAAAAAAAAAAAAAAAGAAAAAAAgAAAAAAAAAAAAAAAAAAhwEEDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAkAAAAAAABAf+Uf+J8AAAA
    AAAD/fwAAAAAAAAAADwAAAAAA0BcEAAAAAPgPAAMAAAA8OwAAAAAAAECjAwAAAAAAAPDPAAAAAAAAAAAAAAAAAAAAAAAAAPf//SEQAwAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAP/////////7APgAAAB8AAAAAAAA3/8AAAAAAAAAAAAAAAD/////AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIADAAAAAAAAAAAAAAAAAAAAAIAAAAA
    AAAAAAAAAAAD/////AAAAAAA8AAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgPc/AAAAwAAAAAAAAAAAAAADAEQIAABgAAAAAAAAAAAAAAAAAAA
    AAAAAADAAAAD//wOAAAAAAMA/AACA/wMAAAAAAAcAAAAAAMgzAAAAACAAAAAAAAAAAH5mAAgQAAAAAAAQAAAAAAAAncECAAAAADBAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAgIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////////////8AAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAD//wAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAADABwAAAAAAAAAAAAAAAAAAAABu8AAAAAAAhwAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAADwAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAADA/wEAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAA/38AAAAAAACAAwAAAAAAeCYAIAAAAAAAAAcAAACA7x8AAAAAAAAACAADAAA
    AAADAfwAeAAAAAAAAAAAAAACA00AAAAAAAAAAAAAAAAAAAAAAAAAAgPgHAAADAAAAAAAAGAEAAADAHx8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/XAAAQAAAAAAAAAA
    AAAD4hQ0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADywAQAAMAAAAAAAAAAAAAD4pwEAAAAAAAAAAAAAAAAovwAAAAAAAAAAAAAAAOC8DwAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAACA/wYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAMAQAAAP4HAAAAAPh5gAB+DgAAAAAA/H8
    DAAAAAAAAAAAAAAAAAAAAAAAAf78AAAAAAAAAAAAA/P///G0AAAAAAAAAAAAAAAAAAAB+tL8AAAAAAAAAAACjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAABgAAAAAAAAA/wEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfAAAAAAAAAH8AAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAACABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYA8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAD+P/nDwA
    AADwAAAAAAAAAAAAAAAAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////9/+P//////HyAAEAAA+P7/AAAAAAAAAAAAAH////nbBwAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAfwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAfwAAAAAAAAAAAAAAAADwBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAQEBAQEBAQEBAQEBAQEBIQEBAQEBAQEBAQEBAQEBAQEBMQFBUWEBAQFxAQGBkaGxw
    RERERERERERERERERERERERERERERERERER0RERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERE
    RERERERERERERERERERERER4QEBAQHxAQERERERERERERERERERERERERERERERERERERERERERERERERERERERERESAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBA
    QEBAQEBARERAQECEiEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBA
    QEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQIxERERERERERERERERERERERERERERERJBERJRAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBARJic
    QEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQKCkqKywtLi8QMDEQEBAQEAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAA//////////////////////////////////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwABgAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAHgkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAADAAAAAAAAD/DwAAAACAAAAIAAIMAGAwQBAAAAQsJCAMAAAAAQAAAFC4AAAAAAAAAOA
    AAAABgAAAAAAAAAAAAAAAGAAAAAAAACEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////+/////////////8PAP/////////////////////////
    /////////PwAAAP8P/////////3/+////////////f/7////////////////g///////+/////////////3///////wf/////DwD//////3///////wD////////////
    /////////////////////////////////////////////////AAAAAAAAAAD//////////////////////x////////9/AAAAAAAAAAAAAAAAAAAAAAAAAP///x8AAAA
    AAAAAAAAAAAAAAAAA//////////////////////////8PAAAAAAAAAAAAAAAAAP8DAAD/////9/9/DwAAAAAAAAAAAAAAAAAAAAAAAP7//////////////wEAAAAAAAA
    AAAAAAAAAAAB/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAD/////////////////////////////////////////AP/////////////////////////
    //////////////wcA////fwAAAAAAAAcA8AD/////////////////////////////////////////////////////////////////DxAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABA/gcAAAAAAAAAAAAAAAAHAP//////D/8BAwA/AAAAAAAAAAAAAAAAAAAAAAAAAP////8B4L///////////9///w8
    A//////+HDwD//xH//////////3/9/////////////////////////////5//////////PwB4////AAAEAABgABAAAAAAAAAAAAAA+P////////////8AAAAAAAD////
    //////z8QJwAAGPAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8PAAAA4P///////////////3v8/////+fH////5////////wAAAAAAAAAAAAAAAAAADwcHAD8
    AAAAAAAAAAAAAAAAAAKYBBG5hbWUAFhVqc29uLXBvaW50ZXItbG9jLndhc20BZwYAEV9fd2FzbV9jYWxsX2N0b3JzAQ5jb21wdXRlX2NvbHVtbgIRanNvbl9wb2ludGV
    ybl9sb2MDD2RlY29kZV9oZXhfcXVhZAQLc2tpcF9tZW1iZXIFEGpzb25fcG9pbnRlcl9sb2MHEgEAD19fc3RhY2tfcG9pbnRlcgkKAQAHLnJvZGF0YQAvCXByb2R1Y2V
    ycwEMcHJvY2Vzc2VkLWJ5AQ5Ib21lYnJldyBjbGFuZwYxOC4xLjgALA90YXJnZXRfZmVhdHVyZXMCKw9tdXRhYmxlLWdsb2JhbHMrCHNpZ24tZXh0
`;

let exports = null;
let memory = null;
const encoder = new TextEncoder();

function updatePosition(json, pointer) {
    // Encode source and pointer as bytes
    const jsonBytes = encoder.encode(json);
    const pointerBytes = encoder.encode(pointer);
    if (jsonBytes.length > (1 << 23)) {
        document.getElementById('output').innerText = 'Max JSON size for demo is 8MB.';
        return;
    }
    if (pointerBytes.length > 1024) {
        document.getElementById('output').innerText = 'Max pointer size is 1024 bytes';
        return;
    }

    // Copy data to heap
    const memArray = new Uint8Array(memory.buffer);
    const pointerPointer = exports.__heap_base.value;
    memArray.subarray(pointerPointer, pointerPointer + pointerBytes.length).set(pointerBytes);
    const jsonPointer = pointerPointer + pointerBytes.length;
    memArray.subarray(jsonPointer, jsonPointer + jsonBytes.length).set(jsonBytes);
    const outputPointer = jsonPointer + jsonBytes.length;

    // Call json_pointern_loc() 
    const result = exports.json_pointern_loc(
        jsonPointer, jsonBytes.length, 
        pointerPointer, pointerBytes.length, 
        outputPointer);

    // Copy position/line/column from heap and output
    let message;
    switch (result) {
        case 0:
            const view = new DataView(memory.buffer);
            const position = view.getUint32(outputPointer, true);
            const line = view.getUint32(outputPointer + 4, true);
            const column = view.getUint32(outputPointer + 8, true);
            message = `Position: ${position}, Line: ${line}, Column: ${column}`;
            break;
        case 1:
            message = 'Source is NULL';
            break;
        case 2:
            message = 'Pointer is NULL';
            break;
        case 3:
            message = 'Pointer is invalid';
            break;
        case 4:
            message = 'Pointer uses unsupported features';
            break;
        case 5:
            message = 'Unable to locate JSON element from pointer';
            break;
        default:
            message = 'Unknown error';
            break;
    }
    document.getElementById('output').innerText = message;
}


window.addEventListener('load', async () => {
    // Initialize JSON editor
    const editor = ace.edit("editor");
    editor.session.setMode("ace/mode/json");
    
    // Initialize WebAssembly
    const wasm = fetch(wasmUri.replace(/\s/g, ''));
    memory = new WebAssembly.Memory({
        initial: 1024,
        maximum: 1024
    });
    const importObject = { 
        env: { memory } 
    };
    const source = await WebAssembly.instantiateStreaming(wasm, importObject);
    exports = source.instance.exports;

    // Attach event listeners to update output on changes
    pointerElement = document.getElementById('pointer');
    editor.session.on('change', () => {
        updatePosition(editor.session.getValue(), pointerElement.value);
    });
    document.getElementById('pointer').addEventListener('input', () => {
        updatePosition(editor.session.getValue(), pointerElement.value);
    })

    // Do an initial calculation
    updatePosition(editor.session.getValue(), pointerElement.value);
});
